#!/bin/bash
for ((i = 1; i <= 128; i*=2))
do
M=$(( (( $i / 8 )) + 1 ))
echo "#BSUB -n $M
#BSUB -W 00:15
#BSUB -o \"./out_files/omp/xs/$i.out\"
#BSUB -e \"./err_files/omp/xs/$i.err\"
#BSUB -R \"span[hosts=1]\"
OMP_NUM_THREADS=$i ./2mm_omp_xs">./xs/$i.lsf
done

for ((i = 1; i <= 128; i*=2))
do
M=$(( (( $i / 8 )) + 1 ))
echo "#BSUB -n $M
#BSUB -W 00:15
#BSUB -o \"./out_files/omp/s/$i.out\"
#BSUB -e \"./err_files/omp/s/$i.err\"
#BSUB -R \"span[hosts=1]\"
OMP_NUM_THREADS=$i ./2mm_omp_s">./s/$i.lsf
done

for ((i = 1; i <= 128; i*=2))
do
M=$(( (( $i / 8 )) + 1 ))
echo "#BSUB -n $M
#BSUB -W 00:15
#BSUB -o \"./out_files/omp/m/$i.out\"
#BSUB -e \"./err_files/omp/m/$i.err\"
#BSUB -R \"span[hosts=1]\"
OMP_NUM_THREADS=$i ./2mm_omp_m">./m/$i.lsf
done

for ((i = 1; i <= 128; i*=2))
do
M=$(( (( $i / 8 )) + 1 ))
echo "#BSUB -n $M
#BSUB -W 00:15
#BSUB -o \"./out_files/omp/l/$i.out\"
#BSUB -e \"./err_files/omp/l/$i.err\"
#BSUB -R \"span[hosts=1]\"
OMP_NUM_THREADS=$i ./2mm_omp_l">./l/$i.lsf
done

for ((i = 1; i <= 128; i*=2))
do
M=$(( (( $i / 8 )) + 1 ))
echo "#BSUB -n $M
#BSUB -W 00:15
#BSUB -o \"./out_files/omp/xl/$i.out\"
#BSUB -e \"./err_files/omp/xl/$i.err\"
#BSUB -R \"span[hosts=1]\"
OMP_NUM_THREADS=$i ./2mm_omp_xl">./xl/$i.lsf
done
